modules:
  scoreboard: true
  languages: true
  lobby: true
  chat: true
  tab: true
  items: true
  nametags: true
  whitelist:
    enabled: false
    worlds:
      world:
        - 'lobby'
        - 'chat'
        - 'items'
        - 'visibility'
        - 'speed'
        - 'doubleJump'
        - 'fly'
        - 'jump'
        - 'joinmessages'
        - 'scoreboard'
        - 'jointp'
        - 'voidtp'

key: 8JRI-OK0R-IF7Y-OPE5

hooks:
  luckperms: false
  skinsrestorer: true

redis:
  enabled: true
  host: "localhost"
  port: 6379
  config:
    maxConnections: 10
    useSSL: false
  auth:
    password: "uqqVbwm/XOY"

data:
  type: sqlite
  mysql:
    host: localhost:3306
    database: core
    user: root
    password: 12345678
  mongodb:
    host: localhost:27017
    database: core
    user: root
    password: 12345678
    uri: 'mongodb://localhost:27017' #use this instead of host, user and password

scoreboard:
  update: 10
  boards:
    default:
      title: '%core_lobby_scoreboard.title%'
      lines:
        - '%core_lobby_scoreboard.lines%'

settings:
  perWorld: true
  longTags: true
  prefix: '&b&lFrozzCore &8» '
  askOnFirstJoin: true
  tpEveryJoin: true
  debug: false
  languages:
    default: en_US
    downloader:
      user: 'FrozzMC'
      repo: 'languages'
      folders:
        - 'v2.0'

lobby:
  spawn: null
  disablePvP: true
  disableDamage: true
  teleportOnVoid: true
  disableInteract: true
  disableWeather: true
  disableDayCycle: true
  disableSpawn: true
  disableHunger: true
  vipMessages: true
  respawn: true

chat:
  colors:
    default: '&7'
    vip: '&e'
  format:
    prefix: '%luckperms_prefix%'
    name: '%player_name%'
    suffix: ' &8» '
    message: '{color}'

vip:
  messages:
    rank: '%luckperms_prefix%%player_name% &fha entrado al servidor.'
    staff: '&c「Staff」%player_name% &fha entrado al servidor.'

tab:
  header: |-
    &fsi xd
  footer: |-
    &fno xddxdx
  update: 20

items:
  onWorldChange: true
  onJoin: true
  onRespawn: true

placeholders:
  network1: '&b&lGatiscordia &f&lNetwork'
  network2: '&b&lG&f&lN &8» &7'