modules:
  scoreboard: true
  languages: true
  lobby: true
  chat: true
  tab: true
  items: true
  nametags: true

hooks:
  luckperms: false
  skinsrestorer: true

data:
  type: sqlite
  mysql:
    host: localhost:3306
    database: frozzcore
    user: root
    password: 12345678

scoreboard:
  update: 10
  boards:
    default:
      title: '%core_lobby_scoreboard.title%'
      lines:
        - '%core_lobby_scoreboard.lines%'

settings:
  perWorld: true
  longTags: true
  prefix: '&b&lFrozzCore &8» '
  askOnFirstJoin: true
  debug: false
  languages:
    default: en_US
    downloader:
      user: 'FrozzMC'
      repo: 'languages'
      folders:
        - 'v2.0'

lobby:
  spawn: null
  disablePvP: true
  disableDamage: true
  teleportOnVoid: true
  disableInteract: true
  disableWeather: true
  disableDayCycle: true
  disableHunger: true
  vipMessages: true
  respawn: true

chat:
  colors:
    default: '&7'
    vip: '&e'
  format:
    prefix: '%luckperms_prefix%'
    name: '%player_name%'
    suffix: ' &8» '
    message: '{color}'

vip:
  messages:
    rank: '%luckperms_prefix%%player_name% &fha entrado al servidor.'
    staff: '&c「Staff」%player_name% &fha entrado al servidor.'

tab:
  header: |-
    &fsi xd
  footer: |-
    &fno xddxdx
  update: 20

items:
  onWorldChange: true
  onJoin: true
  onRespawn: true